POST http://localhost:8080/api/v1/auth/signup
Content-Type: multipart/form-data; boundary=WebKitFormBoundary

--WebKitFormBoundary
Content-Disposition: form-data; name="firstName"

james
--WebKitFormBoundary
Content-Disposition: form-data; name="lastName"

brownson
--WebKitFormBoundary
Content-Disposition: form-data; name="password"

P@ssword123?
--WebKitFormBoundary
Content-Disposition: form-data; name="confirmPassword"

P@ssword123?
--WebKitFormBoundary
Content-Disposition: form-data; name="email"

afiaaniebiet0@gmail.com
--WebKitFormBoundary
Content-Disposition: form-data; name="profilePicture"; filename="dp.jpg"
Content-Type: image/jpeg

< ../../src/test/resources/images/dp.jpg
--WebKitFormBoundary--