POST http://localhost:8080/api/v1/auth/signup
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="request"
Content-Type: application/json

{
"firstName": "aniebiet",
"lastName": "afia",
"password": "Password123?",
"confirmPassword": "Password123?",
"email": "aniebiet@gmail.com"
}


--WebAppBoundary
Content-Disposition: form-data; name="profilePicture"; filename="dp.jpg"
Content-Type: image/jpeg

< ../../src/test/resources/images/dp.jpg
--WebAppBoundary--